CREATE DATABASE IF NOT EXISTS quant_fund
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE quant_fund;

CREATE TABLE IF NOT EXISTS user_account (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  username VARCHAR(64) NOT NULL COMMENT 'Login username',
  password_hash VARCHAR(255) NOT NULL COMMENT 'BCrypt password hash',
  nickname VARCHAR(64) NOT NULL COMMENT 'Display nickname',
  phone VARCHAR(32) DEFAULT NULL COMMENT 'Phone number',
  email VARCHAR(128) DEFAULT NULL COMMENT 'Email address',
  avatar VARCHAR(512) DEFAULT NULL COMMENT 'Avatar URL',
  role VARCHAR(32) NOT NULL DEFAULT 'USER' COMMENT 'User role: USER or ADMIN',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'User status',
  risk_level VARCHAR(32) NOT NULL DEFAULT 'MEDIUM' COMMENT 'User risk preference level',
  last_login_time DATETIME(3) DEFAULT NULL COMMENT 'Last login time',
  last_login_ip VARCHAR(64) DEFAULT NULL COMMENT 'Last login IP',
  register_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Register time',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_account_username (username),
  UNIQUE KEY uk_user_account_phone (phone),
  UNIQUE KEY uk_user_account_email (email),
  KEY idx_user_account_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User account';

CREATE TABLE IF NOT EXISTS portfolio_account (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  user_id BIGINT NOT NULL COMMENT 'Owner user id',
  account_name VARCHAR(128) NOT NULL COMMENT 'Portfolio account name',
  platform_type VARCHAR(32) NOT NULL COMMENT 'Platform type: ALIPAY, EASTMONEY, BROKER, MANUAL',
  total_asset DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Total assets',
  total_invest_amount DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Total invested amount',
  current_profit DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Current profit',
  current_profit_rate DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'Current profit rate percentage',
  daily_profit DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Daily profit',
  cash_position_rate DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'Cash position percentage',
  equity_position_rate DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'Equity fund position percentage',
  bond_position_rate DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'Bond fund position percentage',
  max_single_fund_position_rate DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'Maximum single fund position percentage',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'Account status',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  KEY idx_portfolio_account_user_id (user_id),
  KEY idx_portfolio_account_platform (platform_type),
  KEY idx_portfolio_account_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Portfolio account';

CREATE TABLE IF NOT EXISTS fund_info (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  fund_code VARCHAR(32) NOT NULL COMMENT 'Fund code',
  fund_name VARCHAR(128) NOT NULL COMMENT 'Fund name',
  fund_type VARCHAR(32) NOT NULL COMMENT 'Fund type',
  active_fund TINYINT NOT NULL DEFAULT 0 COMMENT 'Whether actively managed fund',
  tracking_index VARCHAR(128) DEFAULT NULL COMMENT 'Tracking index name',
  manager_name VARCHAR(128) DEFAULT NULL COMMENT 'Fund manager name',
  company_name VARCHAR(128) DEFAULT NULL COMMENT 'Fund company name',
  risk_level VARCHAR(32) DEFAULT NULL COMMENT 'Fund risk level',
  theme_tags VARCHAR(512) DEFAULT NULL COMMENT 'Industry or theme tags',
  manual_category VARCHAR(32) DEFAULT NULL COMMENT 'Manual corrected fund category',
  source_name VARCHAR(64) NOT NULL DEFAULT 'MOCK' COMMENT 'Latest data source name',
  source_update_time DATETIME(3) DEFAULT NULL COMMENT 'Source update time',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  UNIQUE KEY uk_fund_info_code (fund_code),
  KEY idx_fund_info_name (fund_name),
  KEY idx_fund_info_type (fund_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Fund basic information';

CREATE TABLE IF NOT EXISTS fund_nav_daily (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  fund_code VARCHAR(32) NOT NULL COMMENT 'Fund code',
  nav_date DATE NOT NULL COMMENT 'NAV date',
  unit_nav DECIMAL(20,6) NOT NULL COMMENT 'Unit NAV',
  accumulated_nav DECIMAL(20,6) DEFAULT NULL COMMENT 'Accumulated NAV',
  daily_growth_rate DECIMAL(10,4) DEFAULT NULL COMMENT 'Daily growth rate percentage',
  source_name VARCHAR(64) NOT NULL COMMENT 'Data source name',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  UNIQUE KEY uk_fund_nav_daily_code_date (fund_code, nav_date),
  KEY idx_fund_nav_daily_date (nav_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Fund official daily NAV';

CREATE TABLE IF NOT EXISTS market_index_daily (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  index_code VARCHAR(32) NOT NULL COMMENT 'Index code',
  index_name VARCHAR(64) NOT NULL COMMENT 'Index name',
  trade_date DATE NOT NULL COMMENT 'Trade date',
  close_price DECIMAL(20,6) NOT NULL COMMENT 'Close price',
  daily_change_rate DECIMAL(10,4) DEFAULT NULL COMMENT 'Daily change rate percentage',
  source_name VARCHAR(64) NOT NULL COMMENT 'Data source name',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  UNIQUE KEY uk_market_index_daily_code_date (index_code, trade_date),
  KEY idx_market_index_daily_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Market index daily quote';

CREATE TABLE IF NOT EXISTS fund_estimate_intraday (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  fund_code VARCHAR(32) NOT NULL COMMENT 'Fund code',
  estimate_date DATE NOT NULL COMMENT 'Estimate date',
  estimate_nav DECIMAL(20,6) DEFAULT NULL COMMENT 'Estimated NAV',
  estimate_growth_rate DECIMAL(10,4) DEFAULT NULL COMMENT 'Estimated growth rate percentage',
  estimate_time DATETIME(3) NOT NULL COMMENT 'Estimate update time',
  source_name VARCHAR(64) NOT NULL COMMENT 'Data source name',
  `delayed` TINYINT NOT NULL DEFAULT 0 COMMENT 'Whether data is delayed or from cache',
  raw_payload JSON DEFAULT NULL COMMENT 'Raw source payload for troubleshooting',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  KEY idx_fund_estimate_code_time (fund_code, estimate_time),
  KEY idx_fund_estimate_date (estimate_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Fund intraday estimate';

CREATE TABLE IF NOT EXISTS portfolio_intraday_snapshot (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  user_id BIGINT NOT NULL COMMENT 'User id',
  snapshot_date DATE NOT NULL COMMENT 'Snapshot date',
  snapshot_time DATETIME(3) NOT NULL COMMENT 'Snapshot time',
  total_asset DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT 'Total asset at snapshot',
  daily_profit DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT 'Portfolio daily profit at snapshot',
  daily_profit_rate DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'Portfolio daily profit rate percentage',
  source_name VARCHAR(64) NOT NULL DEFAULT 'PORTFOLIO_RECALCULATE' COMMENT 'Snapshot source',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  UNIQUE KEY uk_portfolio_intraday_user_time (user_id, snapshot_time),
  KEY idx_portfolio_intraday_user_date (user_id, snapshot_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Portfolio intraday profit snapshot';

CREATE TABLE IF NOT EXISTS fund_holding (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  user_id BIGINT NOT NULL COMMENT 'Owner user id',
  account_id BIGINT NOT NULL COMMENT 'Portfolio account id',
  fund_code VARCHAR(32) NOT NULL COMMENT 'Fund code',
  fund_name VARCHAR(128) NOT NULL COMMENT 'Fund name',
  fund_type VARCHAR(32) NOT NULL COMMENT 'Fund type',
  active_fund TINYINT NOT NULL DEFAULT 0 COMMENT 'Whether actively managed fund',
  holding_amount DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Holding amount',
  holding_share DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Holding shares',
  holding_cost DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Holding cost',
  current_estimate_nav DECIMAL(20,6) DEFAULT NULL COMMENT 'Current estimated NAV',
  latest_official_nav DECIMAL(20,6) DEFAULT NULL COMMENT 'Latest official NAV',
  holding_profit DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Holding profit',
  holding_profit_rate DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'Holding profit rate percentage',
  daily_profit DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Daily profit',
  holding_days INT NOT NULL DEFAULT 0 COMMENT 'Holding days',
  source_platform VARCHAR(64) DEFAULT NULL COMMENT 'Original platform name',
  regular_investment TINYINT NOT NULL DEFAULT 0 COMMENT 'Whether regular investment',
  core_holding TINYINT NOT NULL DEFAULT 0 COMMENT 'Whether core holding',
  watch_focus TINYINT NOT NULL DEFAULT 0 COMMENT 'Whether focus holding',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  KEY idx_fund_holding_user_id (user_id),
  KEY idx_fund_holding_account_id (account_id),
  KEY idx_fund_holding_fund_code (fund_code),
  KEY idx_fund_holding_user_fund (user_id, fund_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User fund holding';

CREATE TABLE IF NOT EXISTS holding_snapshot (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  user_id BIGINT NOT NULL COMMENT 'Owner user id',
  account_id BIGINT NOT NULL COMMENT 'Portfolio account id',
  holding_id BIGINT DEFAULT NULL COMMENT 'Fund holding id',
  snapshot_date DATE NOT NULL COMMENT 'Snapshot date',
  total_asset DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Total assets at snapshot',
  holding_amount DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Holding amount at snapshot',
  holding_profit DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Holding profit at snapshot',
  daily_profit DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Daily profit at snapshot',
  position_rate DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'Position rate percentage',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  UNIQUE KEY uk_holding_snapshot_holding_date (holding_id, snapshot_date),
  KEY idx_holding_snapshot_user_date (user_id, snapshot_date),
  KEY idx_holding_snapshot_account_date (account_id, snapshot_date),
  KEY idx_holding_snapshot_holding_id (holding_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Holding daily snapshot';

CREATE TABLE IF NOT EXISTS trade_record (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  user_id BIGINT NOT NULL COMMENT 'Owner user id',
  account_id BIGINT NOT NULL COMMENT 'Portfolio account id',
  holding_id BIGINT DEFAULT NULL COMMENT 'Fund holding id',
  fund_code VARCHAR(32) NOT NULL COMMENT 'Fund code',
  fund_name VARCHAR(128) NOT NULL COMMENT 'Fund name',
  trade_type VARCHAR(32) NOT NULL COMMENT 'Trade type: BUY, SELL, REGULAR_INVEST, CONVERT_IN, CONVERT_OUT',
  trade_status VARCHAR(32) NOT NULL DEFAULT 'COMPLETED' COMMENT 'Trade status',
  trade_amount DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Trade amount',
  trade_share DECIMAL(20,4) DEFAULT NULL COMMENT 'Trade shares',
  trade_nav DECIMAL(20,6) DEFAULT NULL COMMENT 'Trade NAV',
  trade_fee DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Trade fee',
  trade_time DATETIME(3) NOT NULL COMMENT 'Trade time',
  related_trade_id BIGINT DEFAULT NULL COMMENT 'Related trade id for conversion',
  remark VARCHAR(512) DEFAULT NULL COMMENT 'Trade remark',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  KEY idx_trade_record_user_id (user_id),
  KEY idx_trade_record_account_id (account_id),
  KEY idx_trade_record_holding_id (holding_id),
  KEY idx_trade_record_type_status (trade_type, trade_status),
  KEY idx_trade_record_trade_time (trade_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Simulated trade record';

CREATE TABLE IF NOT EXISTS investment_plan (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  user_id BIGINT NOT NULL COMMENT 'Owner user id',
  account_id BIGINT NOT NULL COMMENT 'Portfolio account id',
  fund_code VARCHAR(32) NOT NULL COMMENT 'Fund code',
  fund_name VARCHAR(128) NOT NULL COMMENT 'Fund name',
  plan_name VARCHAR(128) NOT NULL COMMENT 'Investment plan name',
  plan_type VARCHAR(32) NOT NULL COMMENT 'Plan type',
  amount DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Planned amount',
  frequency VARCHAR(32) NOT NULL COMMENT 'Investment frequency',
  next_execute_date DATE DEFAULT NULL COMMENT 'Next execute date',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'Plan status',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  KEY idx_investment_plan_user_id (user_id),
  KEY idx_investment_plan_account_id (account_id),
  KEY idx_investment_plan_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Investment plan';

CREATE TABLE IF NOT EXISTS strategy_config (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  user_id BIGINT NOT NULL COMMENT 'Owner user id',
  config_name VARCHAR(128) NOT NULL COMMENT 'Strategy config name',
  strategy_type VARCHAR(64) NOT NULL COMMENT 'Strategy type',
  fund_type VARCHAR(32) DEFAULT NULL COMMENT 'Applicable fund type',
  params_json JSON NOT NULL COMMENT 'Strategy parameters JSON',
  enabled TINYINT NOT NULL DEFAULT 1 COMMENT 'Whether enabled',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  KEY idx_strategy_config_user_id (user_id),
  KEY idx_strategy_config_type (strategy_type),
  KEY idx_strategy_config_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Strategy parameter config';

CREATE TABLE IF NOT EXISTS strategy_signal (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  user_id BIGINT NOT NULL COMMENT 'Owner user id',
  account_id BIGINT DEFAULT NULL COMMENT 'Portfolio account id',
  holding_id BIGINT DEFAULT NULL COMMENT 'Fund holding id',
  fund_code VARCHAR(32) DEFAULT NULL COMMENT 'Fund code',
  signal_type VARCHAR(64) NOT NULL COMMENT 'Signal type',
  action VARCHAR(32) NOT NULL COMMENT 'Suggested action: BUY, SELL, HOLD, CONVERT, WATCH',
  action_text VARCHAR(128) NOT NULL COMMENT 'Action display text',
  suggest_amount DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Suggested amount',
  suggest_ratio DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'Suggested ratio percentage',
  risk_level VARCHAR(32) NOT NULL DEFAULT 'MEDIUM' COMMENT 'Risk level',
  confidence DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'Signal confidence',
  reason_json JSON NOT NULL COMMENT 'Signal reasons JSON',
  signal_time DATETIME(3) NOT NULL COMMENT 'Signal generated time',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  KEY idx_strategy_signal_user_time (user_id, signal_time),
  KEY idx_strategy_signal_fund_code (fund_code),
  KEY idx_strategy_signal_action (action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Strategy signal';

CREATE TABLE IF NOT EXISTS ai_analysis_report (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  user_id BIGINT NOT NULL COMMENT 'Owner user id',
  account_id BIGINT DEFAULT NULL COMMENT 'Portfolio account id',
  holding_id BIGINT DEFAULT NULL COMMENT 'Fund holding id',
  fund_code VARCHAR(32) DEFAULT NULL COMMENT 'Fund code',
  model_name VARCHAR(128) NOT NULL COMMENT 'AI model name',
  action VARCHAR(32) NOT NULL COMMENT 'AI suggested action',
  action_text VARCHAR(128) NOT NULL COMMENT 'AI action display text',
  suggest_amount DECIMAL(20,4) NOT NULL DEFAULT 0.0000 COMMENT 'Suggested amount',
  suggest_ratio DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'Suggested ratio percentage',
  confidence DECIMAL(10,4) NOT NULL DEFAULT 0.0000 COMMENT 'AI confidence',
  risk_level VARCHAR(32) NOT NULL DEFAULT 'MEDIUM' COMMENT 'AI risk level',
  deadline VARCHAR(32) NOT NULL DEFAULT '15:00前' COMMENT 'Suggestion deadline',
  strategy VARCHAR(128) DEFAULT NULL COMMENT 'Triggered strategy',
  reasons_json JSON NOT NULL COMMENT 'AI reasons JSON',
  risks_json JSON NOT NULL COMMENT 'AI risks JSON',
  data_summary TEXT DEFAULT NULL COMMENT 'AI data summary',
  final_conclusion TEXT DEFAULT NULL COMMENT 'AI final conclusion',
  request_payload JSON DEFAULT NULL COMMENT 'Structured AI request payload',
  response_payload JSON DEFAULT NULL COMMENT 'AI raw response payload',
  fallback_used TINYINT NOT NULL DEFAULT 0 COMMENT 'Whether fallback was used',
  analysis_time DATETIME(3) NOT NULL COMMENT 'Analysis time',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  KEY idx_ai_report_user_time (user_id, analysis_time),
  KEY idx_ai_report_fund_code (fund_code),
  KEY idx_ai_report_action (action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI analysis report';

CREATE TABLE IF NOT EXISTS api_call_log (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  user_id BIGINT DEFAULT NULL COMMENT 'Owner user id when applicable',
  provider VARCHAR(64) NOT NULL COMMENT 'External provider name',
  api_name VARCHAR(128) NOT NULL COMMENT 'API name',
  request_url VARCHAR(1024) NOT NULL COMMENT 'Request URL without sensitive query values',
  request_method VARCHAR(16) NOT NULL COMMENT 'Request method',
  success TINYINT NOT NULL DEFAULT 0 COMMENT 'Whether call succeeded',
  status_code INT DEFAULT NULL COMMENT 'HTTP status code',
  error_message VARCHAR(1024) DEFAULT NULL COMMENT 'Error message',
  cost_time_ms BIGINT NOT NULL DEFAULT 0 COMMENT 'Cost time in milliseconds',
  fallback_used TINYINT NOT NULL DEFAULT 0 COMMENT 'Whether fallback was used',
  call_time DATETIME(3) NOT NULL COMMENT 'Call time',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  KEY idx_api_call_log_user_id (user_id),
  KEY idx_api_call_log_provider_time (provider, call_time),
  KEY idx_api_call_log_success (success)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='External API call log';

CREATE TABLE IF NOT EXISTS operation_log (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  user_id BIGINT DEFAULT NULL COMMENT 'Operator user id',
  module VARCHAR(64) NOT NULL COMMENT 'Business module',
  action VARCHAR(128) NOT NULL COMMENT 'Operation action',
  biz_type VARCHAR(64) NOT NULL COMMENT 'Business type',
  request_method VARCHAR(16) NOT NULL COMMENT 'Request method',
  request_uri VARCHAR(512) NOT NULL COMMENT 'Request URI',
  request_params JSON DEFAULT NULL COMMENT 'Masked request parameters',
  response_result JSON DEFAULT NULL COMMENT 'Masked response result',
  ip VARCHAR(64) DEFAULT NULL COMMENT 'Client IP',
  user_agent VARCHAR(512) DEFAULT NULL COMMENT 'User agent',
  success TINYINT NOT NULL DEFAULT 1 COMMENT 'Whether operation succeeded',
  error_message VARCHAR(1024) DEFAULT NULL COMMENT 'Error message',
  cost_time_ms BIGINT NOT NULL DEFAULT 0 COMMENT 'Cost time in milliseconds',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  KEY idx_operation_log_user_id (user_id),
  KEY idx_operation_log_module_action (module, action),
  KEY idx_operation_log_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Operation log';

CREATE TABLE IF NOT EXISTS data_source_config (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  user_id BIGINT DEFAULT NULL COMMENT 'Owner user id for custom config',
  source_name VARCHAR(64) NOT NULL COMMENT 'Data source name',
  base_url VARCHAR(512) NOT NULL COMMENT 'Base URL',
  timeout_ms INT NOT NULL DEFAULT 5000 COMMENT 'Timeout in milliseconds',
  refresh_interval_seconds INT NOT NULL DEFAULT 120 COMMENT 'Default refresh interval seconds',
  rate_limit_per_minute INT NOT NULL DEFAULT 60 COMMENT 'Rate limit per minute',
  enabled TINYINT NOT NULL DEFAULT 1 COMMENT 'Whether enabled',
  priority INT NOT NULL DEFAULT 100 COMMENT 'Lower value means higher priority',
  config_json JSON DEFAULT NULL COMMENT 'Extended configuration JSON',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  KEY idx_data_source_user_id (user_id),
  KEY idx_data_source_name (source_name),
  KEY idx_data_source_enabled_priority (enabled, priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Fund data source config';

CREATE TABLE IF NOT EXISTS risk_profile (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  user_id BIGINT NOT NULL COMMENT 'Owner user id',
  risk_level VARCHAR(32) NOT NULL DEFAULT 'MEDIUM' COMMENT 'Risk preference level',
  max_equity_position_rate DECIMAL(10,4) NOT NULL DEFAULT 70.0000 COMMENT 'Maximum equity position percentage',
  max_single_fund_position_rate DECIMAL(10,4) NOT NULL DEFAULT 25.0000 COMMENT 'Maximum single fund position percentage',
  drawdown_alert_rate DECIMAL(10,4) NOT NULL DEFAULT 8.0000 COMMENT 'Drawdown alert percentage',
  daily_rise_alert_rate DECIMAL(10,4) NOT NULL DEFAULT 2.0000 COMMENT 'Daily rise alert percentage',
  daily_fall_alert_rate DECIMAL(10,4) NOT NULL DEFAULT 2.0000 COMMENT 'Daily fall alert percentage',
  config_json JSON DEFAULT NULL COMMENT 'Extended risk configuration JSON',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  UNIQUE KEY uk_risk_profile_user_id (user_id),
  KEY idx_risk_profile_level (risk_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User risk profile';

CREATE TABLE IF NOT EXISTS scheduler_task_log (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  task_name VARCHAR(128) NOT NULL COMMENT 'Scheduler task name',
  trigger_type VARCHAR(32) NOT NULL COMMENT 'Trigger type: CRON or MANUAL',
  status VARCHAR(32) NOT NULL COMMENT 'Task status: SUCCESS, PARTIAL_SUCCESS, FAILED, SKIPPED',
  start_time DATETIME(3) NOT NULL COMMENT 'Task start time',
  end_time DATETIME(3) DEFAULT NULL COMMENT 'Task end time',
  cost_time_ms BIGINT NOT NULL DEFAULT 0 COMMENT 'Task cost time in milliseconds',
  success_count INT NOT NULL DEFAULT 0 COMMENT 'Successful item count',
  failure_count INT NOT NULL DEFAULT 0 COMMENT 'Failed item count',
  error_message VARCHAR(1024) DEFAULT NULL COMMENT 'Task error summary',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  KEY idx_scheduler_task_name_time (task_name, start_time),
  KEY idx_scheduler_task_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Scheduler task execution log';
