CREATE TABLE IF NOT EXISTS quant_signal (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  user_id BIGINT NOT NULL COMMENT 'Owner user id',
  account_id BIGINT DEFAULT NULL COMMENT 'Portfolio account id',
  holding_id BIGINT DEFAULT NULL COMMENT 'Fund holding id',
  fund_code VARCHAR(32) NOT NULL COMMENT 'Fund code',
  fund_name VARCHAR(128) NOT NULL COMMENT 'Fund name',
  action VARCHAR(32) NOT NULL COMMENT 'BUY, SELL, HOLD, WATCH, CONVERT',
  action_text VARCHAR(128) NOT NULL COMMENT 'Action display text',
  suggest_amount DECIMAL(20,4) NOT NULL DEFAULT 0 COMMENT 'Suggested amount',
  suggest_ratio DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'Suggested ratio percentage',
  risk_level VARCHAR(32) NOT NULL DEFAULT 'MEDIUM' COMMENT 'Risk level',
  confidence DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'Confidence 0-1',
  total_score DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'Total quant score 0-100',
  trend_score DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'Trend score',
  opportunity_score DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'Opportunity score',
  risk_score DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'Risk score',
  position_score DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'Position score',
  momentum_score DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'Momentum score',
  metrics_json JSON NOT NULL COMMENT 'Quant metrics JSON',
  reasons_json JSON NOT NULL COMMENT 'Reasons JSON',
  risks_json JSON NOT NULL COMMENT 'Risks JSON',
  model_name VARCHAR(128) NOT NULL DEFAULT 'QuantRuleEngine' COMMENT 'Model name',
  model_version VARCHAR(64) NOT NULL COMMENT 'Model version',
  trade_date DATE NOT NULL COMMENT 'Trading date of the signal',
  decision_phase VARCHAR(32) NOT NULL COMMENT 'Decision phase',
  request_payload JSON DEFAULT NULL COMMENT 'Request sent to quant engine',
  response_payload JSON DEFAULT NULL COMMENT 'Response from quant engine',
  fallback_used TINYINT NOT NULL DEFAULT 0 COMMENT 'Whether Java fallback was used',
  deadline DATETIME(3) DEFAULT NULL COMMENT 'Signal deadline',
  signal_time DATETIME(3) NOT NULL COMMENT 'Signal time',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  KEY idx_quant_signal_user_time (user_id, signal_time),
  KEY idx_quant_signal_holding_time (holding_id, signal_time),
  KEY idx_quant_signal_fund_code (fund_code),
  KEY idx_quant_signal_action (action),
  KEY idx_quant_signal_model_version (model_version),
  UNIQUE KEY uk_quant_signal_idempotent (user_id, holding_id, trade_date, decision_phase, model_version, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Quant engine signal';

CREATE TABLE IF NOT EXISTS quant_backtest_result (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  strategy_name VARCHAR(128) NOT NULL COMMENT 'Strategy name',
  model_version VARCHAR(64) NOT NULL COMMENT 'Model version',
  fund_code VARCHAR(32) DEFAULT NULL COMMENT 'Fund code',
  fund_name VARCHAR(128) DEFAULT NULL COMMENT 'Fund name',
  fund_type VARCHAR(32) DEFAULT NULL COMMENT 'Fund type',
  start_date DATE NOT NULL COMMENT 'Backtest start date',
  end_date DATE NOT NULL COMMENT 'Backtest end date',
  benchmark_code VARCHAR(32) DEFAULT NULL COMMENT 'Benchmark code',
  total_return_rate DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'Total return percentage',
  annual_return_rate DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'Annual return percentage',
  max_drawdown_rate DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'Max drawdown percentage',
  win_rate DECIMAL(10,4) NOT NULL DEFAULT 0 COMMENT 'Win rate percentage',
  sharpe_ratio DECIMAL(10,4) DEFAULT NULL COMMENT 'Sharpe ratio',
  calmar_ratio DECIMAL(10,4) DEFAULT NULL COMMENT 'Calmar ratio',
  trade_count INT NOT NULL DEFAULT 0 COMMENT 'Trade count',
  result_json JSON NOT NULL COMMENT 'Detailed backtest result',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  PRIMARY KEY (id),
  KEY idx_quant_backtest_strategy (strategy_name, model_version),
  KEY idx_quant_backtest_fund_code (fund_code),
  KEY idx_quant_backtest_date (start_date, end_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Quant backtest result';
