CREATE TABLE IF NOT EXISTS screener_fund_universe (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  fund_code VARCHAR(32) NOT NULL COMMENT 'Fund code',
  fund_name VARCHAR(128) NOT NULL COMMENT 'Fund name',
  fund_type VARCHAR(32) NOT NULL COMMENT 'Fund type',
  share_class VARCHAR(32) DEFAULT NULL COMMENT 'Share class: A/C/E/ETF/LOF etc',
  main_fund_code VARCHAR(32) DEFAULT NULL COMMENT 'Main fund code for duplicate share classes',
  company_name VARCHAR(128) DEFAULT NULL COMMENT 'Fund company',
  manager_name VARCHAR(128) DEFAULT NULL COMMENT 'Fund manager',
  establish_date DATE DEFAULT NULL COMMENT 'Establish date',
  fund_size DECIMAL(20,4) DEFAULT NULL COMMENT 'Fund size in 100M CNY or source unit',
  tracking_index VARCHAR(128) DEFAULT NULL COMMENT 'Tracking index',
  active_fund TINYINT NOT NULL DEFAULT 0 COMMENT 'Whether actively managed fund',
  risk_level VARCHAR(32) DEFAULT NULL COMMENT 'Risk level',
  status VARCHAR(32) NOT NULL DEFAULT 'NORMAL' COMMENT 'NORMAL/LIQUIDATING/TERMINATED/UNKNOWN',
  source_name VARCHAR(64) NOT NULL COMMENT 'Data source name',
  last_sync_time DATETIME(3) DEFAULT NULL COMMENT 'Last source sync time',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_screener_fund_universe_code (fund_code),
  KEY idx_screener_fund_universe_type (fund_type),
  KEY idx_screener_fund_universe_status (status),
  KEY idx_screener_fund_universe_main_code (main_fund_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Fund screener market universe';

CREATE TABLE IF NOT EXISTS screener_fund_nav_daily (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  fund_code VARCHAR(32) NOT NULL COMMENT 'Fund code',
  nav_date DATE NOT NULL COMMENT 'NAV date',
  unit_nav DECIMAL(20,6) NOT NULL COMMENT 'Unit NAV',
  accumulated_nav DECIMAL(20,6) DEFAULT NULL COMMENT 'Accumulated NAV',
  daily_growth_rate DECIMAL(10,4) DEFAULT NULL COMMENT 'Daily growth rate percentage',
  source_name VARCHAR(64) NOT NULL COMMENT 'Data source name',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_screener_nav_code_date (fund_code, nav_date),
  KEY idx_screener_nav_date (nav_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Fund screener daily NAV';

CREATE TABLE IF NOT EXISTS screener_universe_filter (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  fund_code VARCHAR(32) NOT NULL COMMENT 'Fund code',
  included TINYINT NOT NULL DEFAULT 0 COMMENT 'Whether included in scoring universe',
  universe_type VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN' COMMENT 'EQUITY/MIXED/INDEX/BOND/ETF/QDII/UNKNOWN',
  exclude_reason VARCHAR(512) DEFAULT NULL COMMENT 'Exclude reason',
  min_nav_days_passed TINYINT NOT NULL DEFAULT 0,
  size_filter_passed TINYINT NOT NULL DEFAULT 0,
  duplicate_filter_passed TINYINT NOT NULL DEFAULT 0,
  status_filter_passed TINYINT NOT NULL DEFAULT 0,
  last_rebuild_time DATETIME(3) DEFAULT NULL,
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_screener_filter_code (fund_code),
  KEY idx_screener_filter_included_type (included, universe_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Fund screener universe filter';

CREATE TABLE IF NOT EXISTS screener_factor_snapshot (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  fund_code VARCHAR(32) NOT NULL COMMENT 'Fund code',
  factor_date DATE NOT NULL COMMENT 'Factor date',
  return_20d DECIMAL(10,4) DEFAULT NULL,
  return_60d DECIMAL(10,4) DEFAULT NULL,
  return_120d DECIMAL(10,4) DEFAULT NULL,
  return_250d DECIMAL(10,4) DEFAULT NULL,
  annual_return_250d DECIMAL(10,4) DEFAULT NULL,
  volatility_60d DECIMAL(10,4) DEFAULT NULL,
  volatility_120d DECIMAL(10,4) DEFAULT NULL,
  max_drawdown_60d DECIMAL(10,4) DEFAULT NULL,
  max_drawdown_120d DECIMAL(10,4) DEFAULT NULL,
  positive_day_ratio_60d DECIMAL(10,4) DEFAULT NULL,
  trend_slope_60d DECIMAL(10,4) DEFAULT NULL,
  excess_return_60d DECIMAL(10,4) DEFAULT NULL,
  excess_return_120d DECIMAL(10,4) DEFAULT NULL,
  peer_percentile DECIMAL(10,4) DEFAULT NULL,
  fund_size DECIMAL(20,4) DEFAULT NULL,
  nav_sample_size INT NOT NULL DEFAULT 0,
  source_name VARCHAR(64) NOT NULL DEFAULT 'SCREENER',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_screener_factor_code_date (fund_code, factor_date),
  KEY idx_screener_factor_date (factor_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Fund screener factor snapshot';

CREATE TABLE IF NOT EXISTS screener_quality_score (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  fund_code VARCHAR(32) NOT NULL COMMENT 'Fund code',
  score_date DATE NOT NULL COMMENT 'Score date',
  quality_score DECIMAL(10,4) NOT NULL DEFAULT 0,
  return_score DECIMAL(10,4) NOT NULL DEFAULT 0,
  risk_score DECIMAL(10,4) NOT NULL DEFAULT 0,
  stability_score DECIMAL(10,4) NOT NULL DEFAULT 0,
  excess_score DECIMAL(10,4) NOT NULL DEFAULT 0,
  peer_score DECIMAL(10,4) NOT NULL DEFAULT 0,
  liquidity_score DECIMAL(10,4) NOT NULL DEFAULT 0,
  data_score DECIMAL(10,4) NOT NULL DEFAULT 0,
  rank_no INT DEFAULT NULL,
  rank_percentile DECIMAL(10,4) DEFAULT NULL,
  recommend_level VARCHAR(32) NOT NULL DEFAULT 'NEUTRAL' COMMENT 'STRONG/WATCH/NEUTRAL/AVOID',
  reasons_json JSON NOT NULL,
  risks_json JSON NOT NULL,
  model_version VARCHAR(64) NOT NULL DEFAULT 'screener-rule-v1',
  create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_screener_score_code_date (fund_code, score_date),
  KEY idx_screener_score_date_score (score_date, quality_score),
  KEY idx_screener_score_level (recommend_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Fund screener quality score';
